name: Desktop Build
on:
  push:
    tags:
      - '*' # 当push标签时触发
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up output
        id: vars
        run: |
          echo "short_ref=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Checkout
        id: check
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build App
        run: ./gradlew packageDistributionForCurrentOS
      - name: Create Github Release
        if: github.repository == 'MycroftWong/disney-sample'
        uses: taiki-e/create-gh-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.FOR_WORKFLOW_PRACTICE }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'releases/tags/')
        with:
          files: 'build/compose/binaries/**/*.deb'
